version: '3'

services:
  app:
    build: .
    command: npm run start:dev
    ports: 
      - "3000:3000"
      - "3333:3333"
      - "9229:9229"
    volumes:
      - ./:/usr/app

volumes:
  db_data:
    driver: local